name: dart_eval
description: A flexible Dart interpreter written in Dart, enabling code push for AOT Dart apps.
version: 0.0.4
homepage: https://github.com/ethanblake4/dart_eval

environment:
  sdk: '>=2.12.3 <3.0.0'

dependencies:
   analyzer: ^1.5.0
   pedantic: ^1.11.0
   kernel:
     path: ../../../dart-sdk/pkg/kernel
   front_end:
     path: ../../../dart-sdk/pkg/front_end

dev_dependencies:
  test: ^1.14.4
